import os
import datetime
import logging
from app.config import Config
from app.services.llm import summarize_daily_report
from app.services.email import send_email

logger = logging.getLogger(__name__)

from app.services.google_docs import google_doc_client

async def generate_and_send_summary():
    """
    Reads today's report from Google Doc, generates an LLM summary, and sends it via email.
    """
    logger.info("Generating evening summary...")
    
    # Read report content
    report_content = google_doc_client.read_day_content()
        
    if not report_content.strip():
        logger.warning("Google Doc is empty or unreadable. Skipping email.")
        return

    # Generate Summary
    try:
        llm_summary = summarize_daily_report(report_content)
    except Exception as e:
        logger.error(f"LLM summarization failed: {e}")
        llm_summary = {"major_accomplishments": ["Failed to generate LLM summary"], "critical_issues": [str(e)], "next_steps": []}

    # Compose Email
    today = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=5, minutes=30))).strftime("%d-%m-%Y")
    subject = f"daily report — {datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=5, minutes=30))).strftime('%d %b %Y')}"
    
    # Parse structured summary
    # llm_summary is now a dict
    if isinstance(llm_summary, str):
        # Fallback if something went wrong and it returned a string
        formatted_html = llm_summary
    else:
        accomplishments = "".join([f"<li>{item}</li>" for item in llm_summary.get("major_accomplishments", [])])
        issues = "".join([f"<li>{item}</li>" for item in llm_summary.get("critical_issues", [])])
        next_steps = "".join([f"<li>{item}</li>" for item in llm_summary.get("next_steps", [])])
        
        formatted_html = f"""
        <h3>🚀 Major Accomplishments</h3>
        <ul>{accomplishments}</ul>
        
        <h3>🚧 Critical Issues / Blockers</h3>
        <ul>{issues}</ul>
        
        <h3>📝 Next Steps</h3>
        <ul>{next_steps}</ul>
        """

    # Simple HTML wrapper
    body_html = f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #333;">Daily Work Report</h2>
        <p style="color: #666;">Date: {today}</p>
        <hr>
        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px;">
            {formatted_html}
        </div>
        <hr>
        <p style="font-size: 12px; color: #999;">auto-generated by personal assistant</p>
    </div>
    """
    
    # Send Email
    success = send_email(subject, body_html)
    
    if success:
        # Log to report
        log_entry = f"""
📧 Daily Report Sent at {datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=5, minutes=30))).strftime("%H:%M")}

Report emailed to: {", ".join(Config.EMAIL_RECIPIENTS)}

--------------------------------------------------
"""
        google_doc_client.append_entry(log_entry)
